cvzi/genius-lyrics-userscript

GeniusLyrics.js
code enhancement by 
1) textContent instead of createTextNode 
2) setupMain for customization
3) getBoundingClientRect() instead of getClientRects()[0]
=> code enhancement

GeniusLyrics.js
Add function isScrollLyricsEnabled to notify outside whether autoscroll is required or not.
=> Add isScrollLyricsEnabled()

GeniusLyrics.js
Add a class name to differentiate different lyrics containers
=> Add a class name to differentiate different lyrics containers

GeniusLyrics.js
=> General Coding Update

GeniusLyrics.js
Code Update
- not to cache the window object inside the iframe. cache the functions required only
=> Code Update

GeniusLyrics.js
Minor update along with Youtube Genius Lyrics
https://github.com/cvzi/Youtube-Genius-Lyrics-userscript/pull/18
=> Minor update along with Youtube Genius Lyrics

GeniusLyrics.js
add new function "reloadCurrentLyrics" for special use
=> add new function "reloadCurrentLyrics" for special use

GeniusLyrics.js
fix the bug that the automatic selection was not cached which made the lyrics cannot be reloaded 
previous cache `const hitFromCache = getLyricsSelection(..., ...)` was performed from the modified title and artists which might be different with `genius.current.title` and `genius.current.artists`
=> Bug Fixing

GeniusLyrics.js
=> fix as per #26

GeniusLyrics.js
New Coding
Update some coding for the following issues
https://github.com/cvzi/genius-lyrics-userscript/issues/18
https://github.com/cvzi/genius-lyrics-userscript/issues/15
https://github.com/cvzi/Youtube-Genius-Lyrics-userscript/issues/13
New coding makes changes to iframe content styling with options and the cache issues to reduce the disk usage
=> New Coding

GeniusLyrics.js
add genius.minimizeHit.onlyCompleteLyrics to allow showing non-complete lyrics
=> add genius.minimizeHit.onlyCompleteLyrics

GeniusLyrics.js
Feature Added:
a. Size Reduction of HTML Request Text Cache (normally half reduced; 1/4 size only if style substitute is used.)
-> 1. Remove unnecessary html coding
-> 2. Pre-stored SVGs in the script instead of caching (up to 50% reduction)
-> 3. Style Substitute as the iframe content styling is modified by custom settings / functions (up to 75% reduction)
b. Strengthen loading cancel checking
c. SpinnerDOM (SpinnerHolder + Spinner) is now customizable
d. Fuzzy Matching (Implemented in YouTube Genius Lyrics)
e. CancelLoading to remove spinnerDOM + interrupt the loading
Feature Changed:
a. AutoScroll Button CSS
b. Annotation Styling
=> Coding Change

GeniusLyrics.js
modified content styles for both desktop_react and desktop_react_atf
=> modified content styles

GeniusLyrics.js
In YouTube, it is not easy to get the artist name from the title.
By checking the code, it is not necessary to have the artist name.
However, it is still required if the less specific and exact matching is required.
(although I don't think it is necessary as fuzzy matching is introduced)
=> Introduce CompoundTitle as artist(s) could be unknown

GeniusLyrics.js
bug fixing for scrolllyrics and remove unnecessary nested function closures.
[Instrumental Bridge] shall give larger vertical space for scrolling
=> rewrite scrolllyrics and add fixInstrumentalBridge

GeniusLyrics.js
=> fix getTrueWindow() error in YouTube Music

GeniusLyrics.js
`.genius-lyrics-header-container` and `.genius-lyrics-header-content` cannot be generated.
changed to `.LSongHeader__Outer_Container` and `.LSongHeader__Outer`
=> CSS revision for new Genius Desktop Layout

GeniusLyrics.js
Recently experienced that the iframe content cannot be loaded.
Found that the cache has to be removed.
=> clear cache before retry

GeniusLyrics.js
=> Native APIs

GeniusLyrics.js
See https://github.com/cvzi/Youtube-Genius-Lyrics-userscript/issues/56
@cvzi  
1. According https://wiki.greasespot.net/GM.xmlHttpRequest,  adding `responseType` and `overrideMimeType` might help
2. adding `Accept: application/json` might help
3. `Content-Type: application/x-www-form-urlencoded; charset=UTF-8` shall be removed for GET request
If the issue is just sometimes, might be re-fetch the url can help the issue (like try 3 times)
<del>I think for the json response, we might just use `fetch` API to get the content. `GM.xmlHttpRequest` might not be required.</del>
=> Possible Code Fix

GeniusLyrics.js, references/lz-string-demo.html
@cvzi 
The update forces the cache to be lz-string compressed.
This is to avoid data is not compressed.
The cache will be cleared once via CACHEVERSION = 5
All genius lyrics scripts shall be updated at the same time for consistency 
Remember to bump all Spotify, YouTube, YouTube Music 's genius lyrics script version.
https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/pull/33
https://github.com/cvzi/Youtube-Genius-Lyrics-userscript/pull/67
https://github.com/cvzi/Youtube-Music-Genius-Lyrics-userscript/pull/17
----
-----
close #71
=> use LZString

GeniusLyrics.js
close #75 
See https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/issues/34
See https://github.com/cvzi/Youtube-Music-Genius-Lyrics-userscript/issues/18
=> Fix: LZString Option
